services:
  - type: web
    name: AnonAI-bot
    runtime: python
    # آپدیت سریع pip و نصب پکیج‌ها با استفاده از کشِ سرور
    buildCommand: pip install -U pip && pip install -r requirements.txt
    startCommand: python main.py
    buildpacks:
      - url: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
      - url: https://render/python
    envVars:
      # قفل کردن نسخه پایتون برای جلوگیری از کامپایل‌های اضافه و کند
      - key: PYTHON_VERSION
        value: 3.11.9
      # 🤫 خاموش کردن پیام رو اعصابِ آپدیت pip تو لاگ سرور
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"